[project]
name = "catseye-python"
version = "0.1.0"
description = "A python program to visualize and process images of the eye to isolate vessel data."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.4.6",
    "opencv-contrib-python>=5.0.0.93",
    "pillow>=12.2.0",
    "onnxruntime-gpu>=1.28.0",
    #    "ultralytics>=8.4.92",
#    "onnxruntime-directml>=1.24.4",
    "scipy-stubs~=1.18.0",
]

[dependency-groups]
    dev = [
        "briefcase>=0.4.2",
        "wxpython>=4.2.5",
        "pystackreg>=0.2.8",
        "nuitka>=4.1.3",
    #    "toga>=0.5.4",
    #    "ultralytics>=8.4.70",
    ]


[project.scripts]
GUI_test = "GUI:GUI"
CLI = "main:_run_cli"

#[build-system]
#requires = ["setuptools>=78.1.0", "wheel>=0.45.1"]
#build-backend = "setuptools.build_meta"
